version: "3.9"

services:
  ofserv:
    image: notquiteapex/openfortress_server:latest
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - files:/root/.steam/steamcmd

volumes:
    files:
