version: "3.9"

services:
  openfortress_server:
    image: notquiteapex/openfortress_server:latest
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - ./server:/root/.steam/steamcmd
