# syntax=docker/dockerfile:1
# Open Fortress basic server image.
# This builds Open Fortress from a cached image, only updating files as necessary.
FROM notquiteapex/ofsv:latest

# Update Open Fortress.
RUN ./of-update.sh

# Done.
