# syntax=docker/dockerfile:1
# Open Fortress basic server image.
# This builds Open Fortress from a cached image, only updating files as necessary.
FROM notquiteapex/ofsv:_cache

# Update scripts
ADD ./scripts/*.sh ./
ADD ./scripts/*.txt ./

# Update Open Fortress.
RUN ./of-update.sh

# Done.
