# syntax=docker/dockerfile:1
# Open Fortress basic server image.
# This builds Open Fortress from a cached image, only updating files as necessary.
FROM notquiteapex/ofsv:latest

# Update Open Fortress.
RUN ./of-update.sh

# Update gameinfo.txt
RUN sed -i 's+|all_source_engine_paths|..\\Team Fortress 2\\+/root/.steam/steamcmd/tf2/+g' ./sdk/open_fortress/gameinfo.txt

# Done.
