name: Build Open Fortress images with cached images.

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  openfortress_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t notquiteapex/ofsv:latest -f ./dockerfiles/Dockerfile.of
      - name: Docker Push
        run: docker push notquiteapex/ofsv:latest
  openfortress_latest-sm:
    runs-on: ubuntu-latest
    needs: openfortress_latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t notquiteapex/ofsv:latest-sm -f ./dockerfiles/Dockerfile.ofsm
      - name: Docker Push
        run: docker push notquiteapex/ofsv:latest-sm
