name: Build OFServer base image with TF2+SDK.

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  openfortress_tf2sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t notquiteapex/openfortress_server:_tf2sdk -f Dockerfile._tf2sdk
      - name: Docker Push
        run: docker push notquiteapex/openfortress_server:_tf2sdk
